openapi: 3.0.3
info:
  title: Nino360 Leads API
  version: 0.1.0
  description: Public API for Leads management with AI and enrichment.
servers:
  - url: https://api.example.com
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Lead:
      type: object
      properties:
        id: { type: string, format: uuid }
        tenant_id: { type: string, format: uuid }
        stage: { type: string }
        status: { type: string }
        score: { type: number }
        data: { type: object, additionalProperties: true }
        created_at: { type: string, format: date-time }
    LeadCandidate:
      type: object
      properties:
        id: { type: string, format: uuid }
        tenant_id: { type: string, format: uuid }
        source_type: { type: string }
        linkedin_url: { type: string }
        parsed_profile: { type: object }
        confidence: { type: number }
        status: { type: string }
    AIEnrichment:
      type: object
      properties:
        id: { type: string, format: uuid }
        lead_id: { type: string, format: uuid }
        task_type: { type: string }
        status: { type: string }
paths:
  /v1/tenants/{tenantId}/leads:
    get:
      summary: List leads
      parameters:
        - in: path
          name: tenantId
          required: true
          schema: { type: string }
        - in: query
          name: q
          schema: { type: string }
        - in: query
          name: stage
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  data:
                    type: array
                    items: { $ref: '#/components/schemas/Lead' }
    post:
      summary: Create lead
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lead'
      responses:
        '201': { description: Created }
  /v1/tenants/{tenantId}/leads/{leadId}:
    get:
      summary: Get lead by ID
      responses: { '200': { description: OK } }
    put:
      summary: Update lead
      responses: { '200': { description: OK } }
    delete:
      summary: Delete lead
      responses: { '204': { description: No Content } }
  /v1/tenants/{tenantId}/ai/parse:
    post:
      summary: Parse raw profile via LLM adapter
      responses: { '200': { description: OK } }
  /v1/tenants/{tenantId}/ai/enrich:
    post:
      summary: Enqueue enrichment
      responses: { '202': { description: Accepted } }
  /v1/tenants/{tenantId}/sources/linkedin/oauth:
    post:
      summary: Begin LinkedIn OAuth
      responses: { '302': { description: Redirect } }
  /v1/tenants/{tenantId}/sources/csv/upload:
    post:
      summary: Get signed URL for CSV upload
      responses: { '200': { description: OK } }
