// Extracted mock data for CRM dashboard to reduce page module size
export const salesMetrics = {
  totalLeads: {
    value: 2847,
    change: 12.5,
    trend: "up",
    target: 3000,
    progress: 94.9,
    previousValue: 2534,
    weeklyGrowth: 8.2,
    monthlyGrowth: 15.7,
  },
  activeAccounts: {
    value: 1234,
    change: 8.2,
    trend: "up",
    target: 1300,
    progress: 94.9,
    previousValue: 1140,
    weeklyGrowth: 5.1,
    monthlyGrowth: 12.3,
  },
  activeOpportunities: {
    value: 47,
    change: -2.1,
    trend: "down",
    target: 50,
    progress: 94.0,
    previousValue: 48,
    weeklyGrowth: -4.2,
    monthlyGrowth: 6.8,
  },
  revenueForecast: {
    value: 2400000,
    change: 15.3,
    trend: "up",
    target: 2500000,
    progress: 96.0,
    previousValue: 2080000,
    weeklyGrowth: 3.2,
    monthlyGrowth: 18.9,
  },
}

export const pipelineData = [
  {
    stage: "Prospecting",
    count: 45,
    value: 450000,
    color: "#3b82f6",
    percentage: 35,
    conversion: 78,
    avgDealSize: 10000,
    avgTimeInStage: 12,
    deals: [
      { id: 1, name: "TechCorp Solutions", value: 45000, probability: 25 },
      { id: 2, name: "DataFlow Inc", value: 32000, probability: 30 },
      { id: 3, name: "CloudTech Ltd", value: 28000, probability: 20 },
    ],
  },
  {
    stage: "Qualification",
    count: 32,
    value: 680000,
    color: "#8b5cf6",
    percentage: 25,
    conversion: 65,
    avgDealSize: 21250,
    avgTimeInStage: 8,
    deals: [
      { id: 4, name: "InnovateLabs", value: 85000, probability: 45 },
      { id: 5, name: "GlobalStaff", value: 67000, probability: 50 },
      { id: 6, name: "NextGen Systems", value: 54000, probability: 40 },
    ],
  },
  {
    stage: "Proposal",
    count: 18,
    value: 920000,
    color: "#f59e0b",
    percentage: 20,
    conversion: 45,
    avgDealSize: 51111,
    avgTimeInStage: 15,
    deals: [
      { id: 7, name: "Enterprise Solutions", value: 125000, probability: 65 },
      { id: 8, name: "Digital Dynamics", value: 98000, probability: 70 },
      { id: 9, name: "Future Systems", value: 87000, probability: 60 },
    ],
  },
  {
    stage: "Negotiation",
    count: 12,
    value: 350000,
    color: "#ef4444",
    percentage: 15,
    conversion: 72,
    avgDealSize: 29167,
    avgTimeInStage: 6,
    deals: [
      { id: 10, name: "MegaCorp Industries", value: 150000, probability: 85 },
      { id: 11, name: "TechVision Pro", value: 95000, probability: 80 },
      { id: 12, name: "SmartBiz Solutions", value: 75000, probability: 75 },
    ],
  },
  {
    stage: "Closed Won",
    count: 8,
    value: 280000,
    color: "#10b981",
    percentage: 5,
    conversion: 100,
    avgDealSize: 35000,
    avgTimeInStage: 2,
    deals: [
      { id: 13, name: "Success Corp", value: 95000, probability: 100 },
      { id: 14, name: "Victory Systems", value: 85000, probability: 100 },
      { id: 15, name: "Champion Tech", value: 65000, probability: 100 },
    ],
  },
]

export const revenueData = [
  { month: "Jan", revenue: 450000, deals: 12, forecast: 480000, target: 500000, leads: 234, conversion: 5.1 },
  { month: "Feb", revenue: 520000, deals: 15, forecast: 550000, target: 550000, leads: 267, conversion: 5.6 },
  { month: "Mar", revenue: 480000, deals: 13, forecast: 510000, target: 520000, leads: 298, conversion: 4.4 },
  { month: "Apr", revenue: 610000, deals: 18, forecast: 640000, target: 600000, leads: 312, conversion: 5.8 },
  { month: "May", revenue: 550000, deals: 16, forecast: 580000, target: 580000, leads: 289, conversion: 5.5 },
  { month: "Jun", revenue: 670000, deals: 21, forecast: 700000, target: 650000, leads: 334, conversion: 6.3 },
  { month: "Jul", revenue: 720000, deals: 23, forecast: 750000, target: 700000, leads: 356, conversion: 6.5 },
  { month: "Aug", revenue: 680000, deals: 19, forecast: 710000, target: 720000, leads: 341, conversion: 5.6 },
  { month: "Sep", revenue: 750000, deals: 25, forecast: 780000, target: 750000, leads: 378, conversion: 6.6 },
  { month: "Oct", revenue: 820000, deals: 28, forecast: 850000, target: 800000, leads: 392, conversion: 7.1 },
  { month: "Nov", revenue: 780000, deals: 24, forecast: 810000, target: 780000, leads: 367, conversion: 6.5 },
  { month: "Dec", revenue: 890000, deals: 31, forecast: 920000, target: 900000, leads: 421, conversion: 7.4 },
]

export const todaysActivities = [
  {
    id: 1,
    time: "09:00 AM",
    type: "call",
    title: "Discovery call with TechCorp Inc.",
    contact: "John Smith",
    company: "TechCorp Inc.",
    status: "completed",
    priority: "high",
    value: "$450K",
    duration: "45 min",
    outcome: "Positive - Moving to proposal stage",
    nextAction: "Send proposal by EOD",
    avatar: "/placeholder.svg?height=32&width=32&text=JS",
    tags: ["discovery", "enterprise", "hot-lead"],
    notes: "Very interested in our enterprise solution. Decision maker confirmed budget approval.",
    followUpDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
    dealStage: "qualification",
    probability: 75,
  },
  {
    id: 2,
    time: "11:30 AM",
    type: "meeting",
    title: "Product demo for DataFlow Solutions",
    contact: "Sarah Johnson",
    company: "DataFlow Solutions",
    status: "in-progress",
    priority: "high",
    value: "$280K",
    duration: "60 min",
    outcome: "Demo successful - Technical questions answered",
    nextAction: "Schedule follow-up with decision makers",
    avatar: "/placeholder.svg?height=32&width=32&text=SJ",
    tags: ["demo", "technical", "mid-market"],
    notes: "Technical team impressed with integration capabilities. Need to involve procurement.",
    followUpDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    dealStage: "proposal",
    probability: 60,
  },
  {
    id: 3,
    time: "02:00 PM",
    type: "email",
    title: "Follow-up proposal to CloudTech Ltd.",
    contact: "Mike Chen",
    company: "CloudTech Ltd.",
    status: "pending",
    priority: "medium",
    value: "$125K",
    duration: "15 min",
    outcome: "Awaiting response",
    nextAction: "Call if no response by tomorrow",
    avatar: "/placeholder.svg?height=32&width=32&text=MC",
    tags: ["follow-up", "proposal", "small-business"],
    notes: "Sent detailed proposal with pricing options. Waiting for feedback from their team.",
    followUpDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
    dealStage: "proposal",
    probability: 45,
  },
  {
    id: 4,
    time: "03:30 PM",
    type: "call",
    title: "Contract negotiation with InnovateLabs",
    contact: "Lisa Wang",
    company: "InnovateLabs",
    status: "scheduled",
    priority: "high",
    value: "$380K",
    duration: "30 min",
    outcome: "Pending",
    nextAction: "Prepare negotiation points",
    avatar: "/placeholder.svg?height=32&width=32&text=LW",
    tags: ["negotiation", "contract", "enterprise"],
    notes: "Final negotiation call. They want to discuss payment terms and implementation timeline.",
    followUpDate: new Date(Date.now() + 4 * 60 * 60 * 1000),
    dealStage: "negotiation",
    probability: 85,
  },
  {
    id: 5,
    time: "04:45 PM",
    type: "meeting",
    title: "Quarterly review with GlobalStaff",
    contact: "David Brown",
    company: "GlobalStaff",
    status: "scheduled",
    priority: "medium",
    value: "$750K",
    duration: "90 min",
    outcome: "Pending",
    nextAction: "Prepare quarterly metrics",
    avatar: "/placeholder.svg?height=32&width=32&text=DB",
    tags: ["quarterly-review", "existing-client", "upsell"],
    notes: "Existing client quarterly business review. Opportunity to discuss expansion plans.",
    followUpDate: new Date(Date.now() + 6 * 60 * 60 * 1000),
    dealStage: "expansion",
    probability: 70,
  },
]

export const aiInsights = [
  {
    id: 1,
    type: "opportunity",
    title: "High-Value Deal Alert",
    description:
      "TechCorp Inc. shows 95% close probability based on engagement patterns and decision-maker involvement",
    action: "Schedule final negotiation call within 48 hours",
    priority: "urgent",
    confidence: 95,
    impact: "$450K",
    category: "Deal Acceleration",
    timeframe: "Next 2 days",
    riskFactors: ["Budget approval pending", "Competitor evaluation"],
    recommendations: [
      "Highlight ROI benefits in final presentation",
      "Address competitor comparison directly",
      "Offer limited-time incentive",
    ],
    createdAt: new Date(Date.now() - 5 * 60 * 1000),
    isRead: false,
    actionTaken: false,
  },
  {
    id: 2,
    type: "risk",
    title: "Deal at Risk - Immediate Action Required",
    description:
      "DataFlow Solutions hasn't responded in 7 days - 73% probability of deal stalling based on historical patterns",
    action: "Send personalized video message + schedule urgent call",
    priority: "urgent",
    confidence: 87,
    impact: "$280K",
    category: "Risk Mitigation",
    timeframe: "Today",
    riskFactors: ["No response for 7 days", "Decision maker changed", "Budget freeze rumors"],
    recommendations: [
      "Send personalized video message",
      "Reach out to alternative contacts",
      "Offer flexible payment terms",
    ],
    createdAt: new Date(Date.now() - 15 * 60 * 1000),
    isRead: false,
    actionTaken: false,
  },
  {
    id: 3,
    type: "upsell",
    title: "Expansion Opportunity Detected",
    description: "CloudTech Ltd. usage increased 40% this month - perfect timing for expansion conversation",
    action: "Create expansion proposal with 25% discount",
    priority: "high",
    confidence: 78,
    impact: "$125K additional",
    category: "Account Growth",
    timeframe: "This week",
    riskFactors: ["Budget cycle timing"],
    recommendations: [
      "Highlight usage growth metrics",
      "Propose phased expansion plan",
      "Include success story case studies",
    ],
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
    isRead: true,
    actionTaken: false,
  },
  {
    id: 4,
    type: "lead",
    title: "Hot Lead Identified",
    description: "New inbound lead from enterprise segment with high intent signals - 92% match score",
    action: "Assign to top performer within 1 hour",
    priority: "high",
    confidence: 92,
    impact: "$200K potential",
    category: "Lead Qualification",
    timeframe: "Next hour",
    riskFactors: ["Competitor outreach"],
    recommendations: [
      "Immediate phone outreach",
      "Send personalized welcome sequence",
      "Schedule demo within 24 hours",
    ],
    createdAt: new Date(Date.now() - 45 * 60 * 1000),
    isRead: true,
    actionTaken: true,
  },
  {
    id: 5,
    type: "prediction",
    title: "Q4 Revenue Forecast Update",
    description:
      "Based on current pipeline velocity and historical patterns, Q4 revenue likely to exceed target by 12%",
    action: "Review resource allocation for Q1 planning",
    priority: "medium",
    confidence: 84,
    impact: "$300K above target",
    category: "Forecasting",
    timeframe: "End of quarter",
    riskFactors: ["Market conditions", "Team capacity"],
    recommendations: [
      "Prepare for increased demand",
      "Consider hiring additional sales reps",
      "Optimize onboarding process",
    ],
    createdAt: new Date(Date.now() - 60 * 60 * 1000),
    isRead: true,
    actionTaken: false,
  },
]

export const leadSources = [
  { name: "Website", value: 35, color: "#3b82f6", count: 997, conversion: 12.3, cost: 45 },
  { name: "LinkedIn", value: 28, color: "#8b5cf6", count: 798, conversion: 18.7, cost: 67 },
  { name: "Referrals", value: 20, color: "#10b981", count: 569, conversion: 28.4, cost: 23 },
  { name: "Email", value: 12, color: "#f59e0b", count: 342, conversion: 8.9, cost: 12 },
  { name: "Events", value: 5, color: "#ef4444", count: 142, conversion: 22.1, cost: 156 },
]

export const teamPerformance = [
  {
    id: 1,
    name: "Alice Johnson",
    role: "Senior Sales Rep",
    deals: 12,
    revenue: 450000,
    target: 400000,
    avatar: "/placeholder.svg?height=32&width=32&text=AJ",
    performance: 112.5,
    activities: 89,
    callsToday: 15,
    emailsToday: 23,
    meetingsToday: 4,
    status: "active",
    lastActivity: "2 minutes ago",
    topDeals: [
      { name: "TechCorp Inc", value: 85000, stage: "negotiation" },
      { name: "DataFlow Solutions", value: 67000, stage: "proposal" },
    ],
  },
  {
    id: 2,
    name: "Bob Smith",
    role: "Sales Rep",
    deals: 8,
    revenue: 320000,
    target: 350000,
    avatar: "/placeholder.svg?height=32&width=32&text=BS",
    performance: 91.4,
    activities: 67,
    callsToday: 12,
    emailsToday: 18,
    meetingsToday: 2,
    status: "active",
    lastActivity: "15 minutes ago",
    topDeals: [
      { name: "CloudTech Ltd", value: 45000, stage: "qualification" },
      { name: "InnovateLabs", value: 38000, stage: "prospecting" },
    ],
  },
  {
    id: 3,
    name: "Carol Davis",
    role: "Senior Sales Rep",
    deals: 15,
    revenue: 580000,
    target: 500000,
    avatar: "/placeholder.svg?height=32&width=32&text=CD",
    performance: 116.0,
    activities: 102,
    callsToday: 18,
    emailsToday: 31,
    meetingsToday: 6,
    status: "active",
    lastActivity: "5 minutes ago",
    topDeals: [
      { name: "GlobalStaff", value: 125000, stage: "closed-won" },
      { name: "NextGen Systems", value: 95000, stage: "negotiation" },
    ],
  },
  {
    id: 4,
    name: "David Wilson",
    role: "Sales Rep",
    deals: 6,
    revenue: 240000,
    target: 300000,
    avatar: "/placeholder.svg?height=32&width=32&text=DW",
    performance: 80.0,
    activities: 45,
    callsToday: 8,
    emailsToday: 12,
    meetingsToday: 1,
    status: "away",
    lastActivity: "2 hours ago",
    topDeals: [
      { name: "SmartBiz Solutions", value: 32000, stage: "qualification" },
      { name: "Future Systems", value: 28000, stage: "prospecting" },
    ],
  },
]

export const quickActions = [
  {
    id: 1,
    title: "Add New Lead",
    icon: null,
    color: "bg-blue-500",
    description: "Create a new lead entry",
    shortcut: "Ctrl+N",
  },
  {
    id: 2,
    title: "Schedule Meeting",
    icon: null,
    color: "bg-green-500",
    description: "Book a meeting with prospect",
    shortcut: "Ctrl+M",
  },
  {
    id: 3,
    title: "Send Email",
    icon: null,
    color: "bg-purple-500",
    description: "Send follow-up email",
    shortcut: "Ctrl+E",
  },
  {
    id: 4,
    title: "Create Proposal",
    icon: null,
    color: "bg-orange-500",
    description: "Generate new proposal",
    shortcut: "Ctrl+P",
  },
  {
    id: 5,
    title: "Log Call",
    icon: null,
    color: "bg-red-500",
    description: "Record call activity",
    shortcut: "Ctrl+L",
  },
  {
    id: 6,
    title: "Update Deal",
    icon: null,
    color: "bg-indigo-500",
    description: "Modify deal information",
    shortcut: "Ctrl+U",
  },
]
