import {
  Users,
  Calendar,
  FileText,
  Building2,
  UserCheck,
  MessageSquare,
  Target,
  Shield,
  Clock,
  Award,
  GraduationCap,
  Video,
  CheckCircle,
  UserPlus,
  Search,
  Heart,
  Zap,
  Brain,
  Star,
  Handshake,
  Gift,
  Bot,
  Calculator,
  Receipt,
  Wallet,
  BanknoteIcon as BankNote,
  FileSpreadsheet,
  Send,
  Package,
  Globe,
  Layers,
  UserCog,
  Lock,
  Key,
  Eye,
  Bell,
  Server,
  Monitor,
} from "lucide-react"

import {
  BarChart3,
  PieChart,
  TrendingUp,
  BarChart,
  Settings,
  Briefcase,
  DollarSign,
  BookOpen,
  Database,
  TrendingDown,
  CreditCard,
  AlertTriangle,
  HardDrive,
  Workflow,
  Activity,
  Archive,
  Headphones,
  Code,
  Palette,
} from "lucide-react"

export const modulePages = {
  crm: [
    { id: "overview", name: "Overview", path: "/crm", icon: BarChart3, description: "CRM dashboard and overview" },
    {
      id: "dashboard",
      name: "Dashboard",
      path: "/crm/dashboard",
      icon: PieChart,
      description: "CRM analytics dashboard",
    },
    { id: "leads", name: "Leads", path: "/crm/leads", icon: Target, description: "Manage leads and prospects" },
    { id: "contacts", name: "Contacts", path: "/crm/contacts", icon: Users, description: "Contact management" },
    { id: "companies", name: "Companies", path: "/crm/companies", icon: Building2, description: "Company profiles" },
    { id: "pipeline", name: "Pipeline", path: "/crm/pipeline", icon: TrendingUp, description: "Sales pipeline" },
    {
      id: "campaigns",
      name: "Campaigns",
      path: "/crm/campaigns",
      icon: MessageSquare,
      description: "Marketing campaigns",
    },
    {
      id: "engagements",
      name: "Engagements",
      path: "/crm/engagements",
      icon: Handshake,
      description: "Customer engagements",
    },
    {
      id: "calendar",
      name: "Calendar",
      path: "/crm/calendar",
      icon: Calendar,
      description: "Schedule and appointments",
    },
    { id: "documents", name: "Documents", path: "/crm/documents", icon: FileText, description: "Document management" },
    { id: "analytics", name: "Analytics", path: "/crm/analytics", icon: BarChart, description: "CRM analytics" },
    { id: "reports", name: "Reports", path: "/crm/reports", icon: FileSpreadsheet, description: "CRM reports" },
    {
      id: "ai-assistant",
      name: "AI Assistant",
      path: "/crm/ai-assistant",
      icon: Bot,
      description: "AI-powered assistance",
    },
    { id: "settings", name: "Settings", path: "/crm/settings", icon: Settings, description: "CRM configuration" },
  ],
  talent: [
    { id: "overview", name: "Overview", path: "/talent", icon: BarChart3, description: "Talent management overview" },
    {
      id: "dashboard",
      name: "Dashboard",
      path: "/talent/dashboard",
      icon: PieChart,
      description: "Talent analytics dashboard",
    },
    { id: "jobs", name: "Jobs", path: "/talent/jobs", icon: Briefcase, description: "Job postings and management" },
    {
      id: "candidates",
      name: "Candidates",
      path: "/talent/candidates",
      icon: Users,
      description: "Candidate profiles",
    },
    { id: "sourcing", name: "Sourcing", path: "/talent/sourcing", icon: Search, description: "Talent sourcing tools" },
    {
      id: "applicants",
      name: "Applicants",
      path: "/talent/applicants",
      icon: UserPlus,
      description: "Application management",
    },
    {
      id: "interviews",
      name: "Interviews",
      path: "/talent/interviews",
      icon: Video,
      description: "Interview scheduling",
    },
    {
      id: "assessments",
      name: "Assessments",
      path: "/talent/assessments",
      icon: CheckCircle,
      description: "Candidate assessments",
    },
    { id: "offers", name: "Offers", path: "/talent/offers", icon: Gift, description: "Offer management" },
    {
      id: "onboarding",
      name: "Onboarding",
      path: "/talent/onboarding",
      icon: UserCheck,
      description: "Employee onboarding",
    },
    {
      id: "engagement",
      name: "Engagement",
      path: "/talent/engagement",
      icon: Heart,
      description: "Employee engagement",
    },
    { id: "skills", name: "Skills", path: "/talent/skills", icon: Star, description: "Skills management" },
    { id: "analytics", name: "Analytics", path: "/talent/analytics", icon: BarChart, description: "Talent analytics" },
    {
      id: "marketplace",
      name: "Marketplace",
      path: "/talent/marketplace",
      icon: Globe,
      description: "Talent marketplace",
    },
    { id: "community", name: "Community", path: "/talent/community", icon: Users, description: "Talent community" },
    {
      id: "recognition",
      name: "Recognition",
      path: "/talent/recognition",
      icon: Award,
      description: "Employee recognition",
    },
    { id: "automation", name: "Automation", path: "/talent/automation", icon: Zap, description: "Process automation" },
    { id: "ai", name: "AI Assistant", path: "/talent/ai", icon: Brain, description: "AI-powered talent tools" },
    {
      id: "integrations",
      name: "Integrations",
      path: "/talent/integrations",
      icon: Layers,
      description: "Third-party integrations",
    },
  ],
  hrms: [
    { id: "overview", name: "Overview", path: "/hrms", icon: BarChart3, description: "HRMS overview" },
    { id: "dashboard", name: "Dashboard", path: "/hrms/dashboard", icon: PieChart, description: "HR dashboard" },
    { id: "employees", name: "Employees", path: "/hrms/employees", icon: Users, description: "Employee management" },
    { id: "teams", name: "Teams", path: "/hrms/teams", icon: Users, description: "Team management" },
    {
      id: "organization",
      name: "Organization",
      path: "/hrms/organization",
      icon: Building2,
      description: "Organizational structure",
    },
    {
      id: "attendance",
      name: "Attendance",
      path: "/hrms/attendance",
      icon: Clock,
      description: "Attendance tracking",
    },
    {
      id: "performance",
      name: "Performance",
      path: "/hrms/performance",
      icon: TrendingUp,
      description: "Performance management",
    },
    { id: "payroll", name: "Payroll", path: "/hrms/payroll", icon: DollarSign, description: "Payroll management" },
    { id: "benefits", name: "Benefits", path: "/hrms/benefits", icon: Gift, description: "Employee benefits" },
    { id: "training", name: "Training", path: "/hrms/training", icon: BookOpen, description: "Training programs" },
    {
      id: "onboarding",
      name: "Onboarding",
      path: "/hrms/onboarding",
      icon: UserPlus,
      description: "Employee onboarding",
    },
    {
      id: "offboarding",
      name: "Offboarding",
      path: "/hrms/offboarding",
      icon: UserCheck,
      description: "Employee offboarding",
    },
    { id: "analytics", name: "Analytics", path: "/hrms/analytics", icon: BarChart, description: "HR analytics" },
    { id: "reports", name: "Reports", path: "/hrms/reports", icon: FileText, description: "HR reports" },
    {
      id: "ai-assistant",
      name: "AI Assistant",
      path: "/hrms/ai-assistant",
      icon: Bot,
      description: "AI HR assistant",
    },
    { id: "settings", name: "Settings", path: "/hrms/settings", icon: Settings, description: "HRMS settings" },
  ],
  training: [
    { id: "overview", name: "Overview", path: "/training", icon: BarChart3, description: "Training overview" },
    {
      id: "learning",
      name: "Learning Management",
      path: "/training/learning",
      icon: BookOpen,
      description: "Learning management system",
    },
    {
      id: "courses",
      name: "Course Catalog",
      path: "/training/courses",
      icon: GraduationCap,
      description: "Course catalog",
    },
    {
      id: "content",
      name: "Content Creation",
      path: "/training/content",
      icon: Video,
      description: "Content creation tools",
    },
    {
      id: "certifications",
      name: "Certification Management",
      path: "/training/certifications",
      icon: Award,
      description: "Certification tracking",
    },
    {
      id: "progress",
      name: "Progress Tracking",
      path: "/training/progress",
      icon: TrendingUp,
      description: "Learning progress",
    },
    {
      id: "assessments",
      name: "Assessment Center",
      path: "/training/assessments",
      icon: CheckCircle,
      description: "Assessments and quizzes",
    },
    {
      id: "analytics",
      name: "Training Analytics",
      path: "/training/analytics",
      icon: BarChart,
      description: "Training analytics",
    },
    {
      id: "engagement",
      name: "Learner Engagement",
      path: "/training/engagement",
      icon: Heart,
      description: "Learner engagement",
    },
    {
      id: "skills",
      name: "Skills Development",
      path: "/training/skills",
      icon: Star,
      description: "Skills development",
    },
    {
      id: "calendar",
      name: "Training Calendar",
      path: "/training/calendar",
      icon: Calendar,
      description: "Training schedule",
    },
    {
      id: "resources",
      name: "Resource Library",
      path: "/training/resources",
      icon: Database,
      description: "Learning resources",
    },
    {
      id: "compliance",
      name: "Compliance Training",
      path: "/training/compliance",
      icon: Shield,
      description: "Compliance training",
    },
    {
      id: "reports",
      name: "Training Reports",
      path: "/training/reports",
      icon: FileText,
      description: "Training reports",
    },
    {
      id: "ai",
      name: "AI Learning Assistant",
      path: "/training/ai",
      icon: Brain,
      description: "AI learning assistant",
    },
    { id: "settings", name: "Settings", path: "/training/settings", icon: Settings, description: "Training settings" },
  ],
  finance: [
    { id: "overview", name: "Overview", path: "/finance", icon: BarChart3, description: "Finance overview" },
    {
      id: "dashboard",
      name: "Dashboard",
      path: "/finance/dashboard",
      icon: PieChart,
      description: "Financial dashboard",
    },
    { id: "revenue", name: "Revenue", path: "/finance/revenue", icon: TrendingUp, description: "Revenue management" },
    {
      id: "expenses",
      name: "Expenses",
      path: "/finance/expenses",
      icon: TrendingDown,
      description: "Expense tracking",
    },
    { id: "payroll", name: "Payroll", path: "/finance/payroll", icon: DollarSign, description: "Payroll processing" },
    {
      id: "invoicing",
      name: "Invoicing",
      path: "/finance/invoicing",
      icon: Receipt,
      description: "Invoice management",
    },
    {
      id: "budgeting",
      name: "Budgeting",
      path: "/finance/budgeting",
      icon: Calculator,
      description: "Budget planning",
    },
    {
      id: "planning",
      name: "Financial Planning",
      path: "/finance/planning",
      icon: Target,
      description: "Financial planning",
    },
    {
      id: "cashflow",
      name: "Cash Flow",
      path: "/finance/cashflow",
      icon: Wallet,
      description: "Cash flow management",
    },
    {
      id: "payable",
      name: "Accounts Payable",
      path: "/finance/payable",
      icon: CreditCard,
      description: "Accounts payable",
    },
    {
      id: "receivable",
      name: "Accounts Receivable",
      path: "/finance/receivable",
      icon: BankNote,
      description: "Accounts receivable",
    },
    { id: "tax", name: "Tax Management", path: "/finance/tax", icon: FileSpreadsheet, description: "Tax management" },
    {
      id: "reports",
      name: "Financial Reports",
      path: "/finance/reports",
      icon: FileText,
      description: "Financial reports",
    },
    {
      id: "analytics",
      name: "Analytics",
      path: "/finance/analytics",
      icon: BarChart,
      description: "Financial analytics",
    },
    { id: "settings", name: "Settings", path: "/finance/settings", icon: Settings, description: "Finance settings" },
  ],
  vms: [
    { id: "overview", name: "Overview", path: "/vms", icon: BarChart3, description: "VMS overview" },
    {
      id: "vendors",
      name: "Vendor Management",
      path: "/vms/vendors",
      icon: Building2,
      description: "Vendor management",
    },
    { id: "jobs", name: "Job Distribution", path: "/vms/jobs", icon: Send, description: "Job distribution" },
    {
      id: "submissions",
      name: "Submission Tracking",
      path: "/vms/submissions",
      icon: Package,
      description: "Submission tracking",
    },
    {
      id: "candidates",
      name: "Candidate Management",
      path: "/vms/candidates",
      icon: Users,
      description: "Candidate management",
    },
    {
      id: "timesheets",
      name: "Timesheet Management",
      path: "/vms/timesheets",
      icon: Clock,
      description: "Timesheet management",
    },
    {
      id: "invoicing",
      name: "Invoice Processing",
      path: "/vms/invoicing",
      icon: Receipt,
      description: "Invoice processing",
    },
    {
      id: "compliance",
      name: "Compliance Tracking",
      path: "/vms/compliance",
      icon: Shield,
      description: "Compliance tracking",
    },
    {
      id: "analytics",
      name: "Performance Analytics",
      path: "/vms/analytics",
      icon: BarChart,
      description: "VMS analytics",
    },
    {
      id: "scorecards",
      name: "Vendor Scorecards",
      path: "/vms/scorecards",
      icon: Star,
      description: "Vendor scorecards",
    },
    {
      id: "contracts",
      name: "Contract Management",
      path: "/vms/contracts",
      icon: FileText,
      description: "Contract management",
    },
    { id: "rates", name: "Rate Management", path: "/vms/rates", icon: DollarSign, description: "Rate management" },
    { id: "reports", name: "Reporting", path: "/vms/reports", icon: FileSpreadsheet, description: "VMS reports" },
    { id: "settings", name: "Settings", path: "/vms/settings", icon: Settings, description: "VMS settings" },
  ],
  bench: [
    { id: "overview", name: "Overview", path: "/bench", icon: BarChart3, description: "Bench overview" },
    {
      id: "available",
      name: "Available Resources",
      path: "/bench/available",
      icon: Users,
      description: "Available resources",
    },
    { id: "skills", name: "Skills Matrix", path: "/bench/skills", icon: Star, description: "Skills matrix" },
    {
      id: "utilization",
      name: "Utilization Tracking",
      path: "/bench/utilization",
      icon: TrendingUp,
      description: "Utilization tracking",
    },
    {
      id: "analytics",
      name: "Bench Analytics",
      path: "/bench/analytics",
      icon: BarChart,
      description: "Bench analytics",
    },
    {
      id: "planning",
      name: "Resource Planning",
      path: "/bench/planning",
      icon: Calendar,
      description: "Resource planning",
    },
    {
      id: "allocation",
      name: "Allocation Management",
      path: "/bench/allocation",
      icon: Target,
      description: "Allocation management",
    },
    { id: "reports", name: "Bench Reports", path: "/bench/reports", icon: FileText, description: "Bench reports" },
    { id: "settings", name: "Settings", path: "/bench/settings", icon: Settings, description: "Bench settings" },
  ],
  hotlist: [
    { id: "overview", name: "Overview", path: "/hotlist", icon: BarChart3, description: "Hotlist overview" },
    {
      id: "priority",
      name: "Priority Requirements",
      path: "/hotlist/priority",
      icon: AlertTriangle,
      description: "Priority requirements",
    },
    {
      id: "requirements",
      name: "Hot Requirements",
      path: "/hotlist/requirements",
      icon: Target,
      description: "Hot requirements",
    },
    { id: "urgent", name: "Urgent Positions", path: "/hotlist/urgent", icon: Clock, description: "Urgent positions" },
    {
      id: "clients",
      name: "Client Priorities",
      path: "/hotlist/clients",
      icon: Building2,
      description: "Client priorities",
    },
    {
      id: "analytics",
      name: "Hotlist Analytics",
      path: "/hotlist/analytics",
      icon: BarChart,
      description: "Hotlist analytics",
    },
    {
      id: "escalation",
      name: "Escalation Management",
      path: "/hotlist/escalation",
      icon: TrendingUp,
      description: "Escalation management",
    },
    {
      id: "reports",
      name: "Priority Reports",
      path: "/hotlist/reports",
      icon: FileText,
      description: "Priority reports",
    },
    { id: "settings", name: "Settings", path: "/hotlist/settings", icon: Settings, description: "Hotlist settings" },
  ],
  tenant: [
    { id: "overview", name: "Overview", path: "/tenant", icon: BarChart3, description: "Tenant overview" },
    { id: "dashboard", name: "Dashboard", path: "/tenant/dashboard", icon: PieChart, description: "Tenant dashboard" },
    {
      id: "directory",
      name: "Tenant Directory",
      path: "/tenant/directory",
      icon: Building2,
      description: "Tenant directory",
    },
    {
      id: "onboarding",
      name: "Tenant Onboarding",
      path: "/tenant/onboarding",
      icon: UserPlus,
      description: "Tenant onboarding",
    },
    { id: "users", name: "User Management", path: "/tenant/users", icon: Users, description: "User management" },
    {
      id: "analytics",
      name: "Tenant Analytics",
      path: "/tenant/analytics",
      icon: BarChart3,
      description: "Tenant analytics",
    },
    {
      id: "configuration",
      name: "Configuration",
      path: "/tenant/configuration",
      icon: Settings,
      description: "Tenant configuration",
    },
    {
      id: "security",
      name: "Security Management",
      path: "/tenant/security",
      icon: Shield,
      description: "Security management",
    },
    { id: "access", name: "Access Control", path: "/tenant/access", icon: Lock, description: "Access control" },
    {
      id: "billing",
      name: "Billing & Subscription",
      path: "/tenant/billing",
      icon: CreditCard,
      description: "Billing management",
    },
    { id: "data", name: "Data Management", path: "/tenant/data", icon: Database, description: "Data management" },
    {
      id: "integrations",
      name: "Integrations",
      path: "/tenant/integrations",
      icon: Layers,
      description: "Integration management",
    },
    {
      id: "notifications",
      name: "Notifications",
      path: "/tenant/notifications",
      icon: Bell,
      description: "Notification settings",
    },
    { id: "audit", name: "Audit Logs", path: "/tenant/audit", icon: FileText, description: "Audit logs" },
    {
      id: "workflows",
      name: "Workflows",
      path: "/tenant/workflows",
      icon: Workflow,
      description: "Workflow management",
    },
    {
      id: "monitoring",
      name: "System Monitoring",
      path: "/tenant/monitoring",
      icon: Activity,
      description: "System monitoring",
    },
    { id: "reports", name: "Reports", path: "/tenant/reports", icon: FileText, description: "Tenant reports" },
    {
      id: "backup",
      name: "Backup & Recovery",
      path: "/tenant/backup",
      icon: Archive,
      description: "Backup management",
    },
    {
      id: "compliance",
      name: "Compliance",
      path: "/tenant/compliance",
      icon: Shield,
      description: "Compliance management",
    },
    {
      id: "support",
      name: "Support Center",
      path: "/tenant/support",
      icon: Headphones,
      description: "Support center",
    },
    { id: "api", name: "API Management", path: "/tenant/api", icon: Code, description: "API management" },
    {
      id: "customization",
      name: "Customization",
      path: "/tenant/customization",
      icon: Palette,
      description: "Platform customization",
    },
    {
      id: "performance",
      name: "Performance Metrics",
      path: "/tenant/performance",
      icon: TrendingUp,
      description: "Performance metrics",
    },
    { id: "scaling", name: "Auto Scaling", path: "/tenant/scaling", icon: TrendingUp, description: "Auto scaling" },
    {
      id: "health",
      name: "Health Check",
      path: "/tenant/health",
      icon: CheckCircle,
      description: "Health monitoring",
    },
  ],
  admin: [
    { id: "overview", name: "Overview", path: "/admin", icon: BarChart3, description: "Admin overview" },
    { id: "dashboard", name: "Dashboard", path: "/admin/dashboard", icon: PieChart, description: "Admin dashboard" },
    { id: "system", name: "System Management", path: "/admin/system", icon: Server, description: "System management" },
    {
      id: "users",
      name: "User Administration",
      path: "/admin/users",
      icon: UserCog,
      description: "User administration",
    },
    {
      id: "tenants",
      name: "Tenant Management",
      path: "/admin/tenants",
      icon: Building2,
      description: "Tenant management",
    },
    {
      id: "modules",
      name: "Module Management",
      path: "/admin/modules",
      icon: Package,
      description: "Module management",
    },
    {
      id: "security",
      name: "Security Management",
      path: "/admin/security",
      icon: Shield,
      description: "Security management",
    },
    { id: "access", name: "Access Control", path: "/admin/access", icon: Lock, description: "Access control" },
    { id: "roles", name: "Role Management", path: "/admin/roles", icon: Key, description: "Role management" },
    {
      id: "permissions",
      name: "Permissions",
      path: "/admin/permissions",
      icon: Eye,
      description: "Permission management",
    },
    { id: "audit", name: "Audit Logs", path: "/admin/audit", icon: FileText, description: "Audit logs" },
    {
      id: "monitoring",
      name: "System Monitoring",
      path: "/admin/monitoring",
      icon: Monitor,
      description: "System monitoring",
    },
    {
      id: "performance",
      name: "Performance Metrics",
      path: "/admin/performance",
      icon: Activity,
      description: "Performance metrics",
    },
    { id: "health", name: "System Health", path: "/admin/health", icon: CheckCircle, description: "System health" },
    {
      id: "resources",
      name: "Resource Usage",
      path: "/admin/resources",
      icon: HardDrive,
      description: "Resource usage",
    },
    { id: "api", name: "API Management", path: "/admin/api", icon: Code, description: "API management" },
    {
      id: "integrations",
      name: "Integration Hub",
      path: "/admin/integrations",
      icon: Layers,
      description: "Integration hub",
    },
    {
      id: "notifications",
      name: "Notification Center",
      path: "/admin/notifications",
      icon: Bell,
      description: "Notification center",
    },
    {
      id: "billing",
      name: "Billing Management",
      path: "/admin/billing",
      icon: CreditCard,
      description: "Billing management",
    },
    {
      id: "licenses",
      name: "License Management",
      path: "/admin/licenses",
      icon: Award,
      description: "License management",
    },
    {
      id: "backup",
      name: "Backup & Recovery",
      path: "/admin/backup",
      icon: Archive,
      description: "Backup management",
    },
    { id: "data", name: "Data Management", path: "/admin/data", icon: Database, description: "Data management" },
    {
      id: "compliance",
      name: "Compliance Center",
      path: "/admin/compliance",
      icon: Shield,
      description: "Compliance center",
    },
    {
      id: "support",
      name: "Support Management",
      path: "/admin/support",
      icon: Headphones,
      description: "Support management",
    },
    {
      id: "settings",
      name: "System Settings",
      path: "/admin/settings",
      icon: Settings,
      description: "System settings",
    },
  ],
  settings: [
    {
      id: "overview",
      name: "Overview",
      path: "/settings",
      icon: BarChart3,
      description: "Settings overview",
      status: "active",
    },
    {
      id: "general",
      name: "General Settings",
      path: "/settings/general",
      icon: Settings,
      description: "General platform settings",
      status: "active",
    },
    {
      id: "preferences",
      name: "User Preferences",
      path: "/settings/preferences",
      icon: UserCog,
      description: "User preferences and customization",
      status: "active",
    },
    {
      id: "notifications",
      name: "Notifications",
      path: "/settings/notifications",
      icon: Bell,
      description: "Notification settings",
      status: "active",
    },
    {
      id: "integrations",
      name: "Integrations",
      path: "/settings/integrations",
      icon: Layers,
      description: "Third-party integrations",
      status: "active",
    },
    {
      id: "api",
      name: "API Management",
      path: "/settings/api",
      icon: Key,
      description: "API keys and management",
      status: "active",
    },
    {
      id: "security",
      name: "Security Settings",
      path: "/settings/security",
      icon: Shield,
      description: "Security and privacy settings",
      status: "active",
    },
    {
      id: "backup",
      name: "Backup Settings",
      path: "/settings/backup",
      icon: HardDrive,
      description: "Backup and recovery settings",
      status: "active",
    },
    {
      id: "logs",
      name: "System Logs",
      path: "/settings/logs",
      icon: FileText,
      description: "System logs and audit trails",
      status: "active",
    },
  ],
}
