// RBAC Permission definitions and utilities

export const PERMISSIONS = {
  // Admin Module
  ADMIN_DASHBOARD_VIEW: "admin.dashboard.view",
  ADMIN_USERS_READ: "admin.users.read",
  ADMIN_USERS_CREATE: "admin.users.create",
  ADMIN_USERS_UPDATE: "admin.users.update",
  ADMIN_USERS_DELETE: "admin.users.delete",
  ADMIN_USERS_INVITE: "admin.users.invite",
  ADMIN_TENANTS_READ: "admin.tenants.read",
  ADMIN_TENANTS_CREATE: "admin.tenants.create",
  ADMIN_TENANTS_UPDATE: "admin.tenants.update",
  ADMIN_TENANTS_DELETE: "admin.tenants.delete",
  ADMIN_ROLES_READ: "admin.roles.read",
  ADMIN_ROLES_CREATE: "admin.roles.create",
  ADMIN_ROLES_UPDATE: "admin.roles.update",
  ADMIN_ROLES_DELETE: "admin.roles.delete",
  ADMIN_PERMISSIONS_READ: "admin.permissions.read",
  ADMIN_PERMISSIONS_ASSIGN: "admin.permissions.assign",
  ADMIN_AUDIT_READ: "admin.audit.read",

  // Tenant Module
  TENANT_DASHBOARD_VIEW: "tenant.dashboard.view",
  TENANT_SETTINGS_READ: "tenant.settings.read",
  TENANT_SETTINGS_UPDATE: "tenant.settings.update",
  TENANT_BRANDING_READ: "tenant.branding.read",
  TENANT_BRANDING_UPDATE: "tenant.branding.update",
  TENANT_BILLING_READ: "tenant.billing.read",
  TENANT_BILLING_UPDATE: "tenant.billing.update",
  TENANT_DIRECTORY_READ: "tenant.directory.read",
  TENANT_DIRECTORY_UPDATE: "tenant.directory.update",

  // CRM Module
  CRM_DASHBOARD_VIEW: "crm.dashboard.view",
  CRM_CLIENTS_READ: "crm.clients.read",
  CRM_CLIENTS_CREATE: "crm.clients.create",
  CRM_CLIENTS_UPDATE: "crm.clients.update",
  CRM_CLIENTS_DELETE: "crm.clients.delete",
  CRM_CLIENTS_EXPORT: "crm.clients.export",
  CRM_CONTACTS_READ: "crm.contacts.read",
  CRM_CONTACTS_CREATE: "crm.contacts.create",
  CRM_CONTACTS_UPDATE: "crm.contacts.update",
  CRM_CONTACTS_DELETE: "crm.contacts.delete",

  // Talent/ATS Module
  TALENT_DASHBOARD_VIEW: "talent.dashboard.view",
  TALENT_CANDIDATES_READ: "talent.candidates.read",
  TALENT_CANDIDATES_CREATE: "talent.candidates.create",
  TALENT_CANDIDATES_UPDATE: "talent.candidates.update",
  TALENT_CANDIDATES_DELETE: "talent.candidates.delete",
  TALENT_CANDIDATES_EXPORT: "talent.candidates.export",
  TALENT_JOBS_READ: "talent.jobs.read",
  TALENT_JOBS_CREATE: "talent.jobs.create",
  TALENT_JOBS_UPDATE: "talent.jobs.update",
  TALENT_JOBS_DELETE: "talent.jobs.delete",
  TALENT_PIPELINES_READ: "talent.pipelines.read",
  TALENT_PIPELINES_UPDATE: "talent.pipelines.update",
  TALENT_INTERVIEWS_READ: "talent.interviews.read",
  TALENT_INTERVIEWS_CREATE: "talent.interviews.create",
  TALENT_INTERVIEWS_UPDATE: "talent.interviews.update",
  TALENT_INTERVIEWS_DELETE: "talent.interviews.delete",

  // Bench Module
  BENCH_DASHBOARD_VIEW: "bench.dashboard.view",
  BENCH_CONSULTANTS_READ: "bench.consultants.read",
  BENCH_CONSULTANTS_CREATE: "bench.consultants.create",
  BENCH_CONSULTANTS_UPDATE: "bench.consultants.update",
  BENCH_CONSULTANTS_DELETE: "bench.consultants.delete",
  BENCH_MARKETING_READ: "bench.marketing.read",
  BENCH_MARKETING_CREATE: "bench.marketing.create",
  BENCH_MARKETING_UPDATE: "bench.marketing.update",
  BENCH_SUBMISSIONS_READ: "bench.submissions.read",
  BENCH_SUBMISSIONS_CREATE: "bench.submissions.create",
  BENCH_SUBMISSIONS_UPDATE: "bench.submissions.update",
  BENCH_PLACEMENTS_READ: "bench.placements.read",
  BENCH_PLACEMENTS_CREATE: "bench.placements.create",
  BENCH_PLACEMENTS_UPDATE: "bench.placements.update",

  // VMS Module
  VMS_DASHBOARD_VIEW: "vms.dashboard.view",
  VMS_VENDORS_READ: "vms.vendors.read",
  VMS_VENDORS_CREATE: "vms.vendors.create",
  VMS_VENDORS_UPDATE: "vms.vendors.update",
  VMS_VENDORS_DELETE: "vms.vendors.delete",
  VMS_COMPLIANCE_READ: "vms.compliance.read",
  VMS_COMPLIANCE_UPDATE: "vms.compliance.update",
  VMS_INVOICES_READ: "vms.invoices.read",
  VMS_INVOICES_CREATE: "vms.invoices.create",
  VMS_INVOICES_UPDATE: "vms.invoices.update",
  VMS_RATECARDS_READ: "vms.ratecards.read",
  VMS_RATECARDS_UPDATE: "vms.ratecards.update",

  // Finance Module
  FINANCE_DASHBOARD_VIEW: "finance.dashboard.view",
  FINANCE_INVOICES_READ: "finance.invoices.read",
  FINANCE_INVOICES_CREATE: "finance.invoices.create",
  FINANCE_INVOICES_UPDATE: "finance.invoices.update",
  FINANCE_INVOICES_DELETE: "finance.invoices.delete",
  FINANCE_INVOICES_APPROVE: "finance.invoices.approve",
  FINANCE_EXPENSES_READ: "finance.expenses.read",
  FINANCE_EXPENSES_CREATE: "finance.expenses.create",
  FINANCE_EXPENSES_UPDATE: "finance.expenses.update",
  FINANCE_EXPENSES_DELETE: "finance.expenses.delete",
  FINANCE_EXPENSES_APPROVE: "finance.expenses.approve",
  FINANCE_REPORTS_READ: "finance.reports.read",

  // Projects Module
  PROJECTS_DASHBOARD_VIEW: "projects.dashboard.view",
  PROJECTS_READ: "projects.read",
  PROJECTS_CREATE: "projects.create",
  PROJECTS_UPDATE: "projects.update",
  PROJECTS_DELETE: "projects.delete",
  PROJECTS_ASSIGNMENTS_READ: "projects.assignments.read",
  PROJECTS_ASSIGNMENTS_CREATE: "projects.assignments.create",
  PROJECTS_ASSIGNMENTS_UPDATE: "projects.assignments.update",
  PROJECTS_ASSIGNMENTS_DELETE: "projects.assignments.delete",

  // Reports Module
  REPORTS_VIEW: "reports.view",
  REPORTS_EXPORT: "reports.export",
  REPORTS_ANALYTICS_VIEW: "reports.analytics.view",

  // Settings Module
  SETTINGS_PROFILE_READ: "settings.profile.read",
  SETTINGS_PROFILE_UPDATE: "settings.profile.update",
  SETTINGS_SECURITY_READ: "settings.security.read",
  SETTINGS_SECURITY_UPDATE: "settings.security.update",
  SETTINGS_NOTIFICATIONS_READ: "settings.notifications.read",
  SETTINGS_NOTIFICATIONS_UPDATE: "settings.notifications.update",

  // HRMS Module
  HRMS_DASHBOARD_VIEW: "hrms.dashboard.view",
  HRMS_EMPLOYEES_READ: "hrms.employees.read",
  HRMS_EMPLOYEES_CREATE: "hrms.employees.create",
  HRMS_EMPLOYEES_UPDATE: "hrms.employees.update",
  HRMS_EMPLOYEES_DELETE: "hrms.employees.delete",
  HRMS_EMPLOYEES_EXPORT: "hrms.employees.export",
  HRMS_ASSIGNMENTS_READ: "hrms.assignments.read",
  HRMS_ASSIGNMENTS_CREATE: "hrms.assignments.create",
  HRMS_ASSIGNMENTS_UPDATE: "hrms.assignments.update",
  HRMS_ASSIGNMENTS_DELETE: "hrms.assignments.delete",
  HRMS_ATTENDANCE_READ: "hrms.attendance.read",
  HRMS_ATTENDANCE_CREATE: "hrms.attendance.create",
  HRMS_ATTENDANCE_UPDATE: "hrms.attendance.update",
  HRMS_ATTENDANCE_APPROVE: "hrms.attendance.approve",
  HRMS_TIMESHEETS_READ: "hrms.timesheets.read",
  HRMS_TIMESHEETS_CREATE: "hrms.timesheets.create",
  HRMS_TIMESHEETS_UPDATE: "hrms.timesheets.update",
  HRMS_TIMESHEETS_APPROVE: "hrms.timesheets.approve",
  HRMS_TIMESHEETS_EXPORT: "hrms.timesheets.export",
  HRMS_ONBOARDING_READ: "hrms.onboarding.read",
  HRMS_ONBOARDING_CREATE: "hrms.onboarding.create",
  HRMS_ONBOARDING_UPDATE: "hrms.onboarding.update",
  HRMS_OFFBOARDING_READ: "hrms.offboarding.read",
  HRMS_OFFBOARDING_CREATE: "hrms.offboarding.create",
  HRMS_OFFBOARDING_UPDATE: "hrms.offboarding.update",
  HRMS_DOCUMENTS_READ: "hrms.documents.read",
  HRMS_DOCUMENTS_CREATE: "hrms.documents.create",
  HRMS_DOCUMENTS_UPDATE: "hrms.documents.update",
  HRMS_DOCUMENTS_DELETE: "hrms.documents.delete",
  HRMS_DOCUMENTS_SIGN: "hrms.documents.sign",
  HRMS_IMMIGRATION_READ: "hrms.immigration.read",
  HRMS_IMMIGRATION_CREATE: "hrms.immigration.create",
  HRMS_IMMIGRATION_UPDATE: "hrms.immigration.update",
  HRMS_I9_READ: "hrms.i9.read",
  HRMS_I9_CREATE: "hrms.i9.create",
  HRMS_I9_UPDATE: "hrms.i9.update",
  HRMS_I9_VERIFY: "hrms.i9.verify",
  HRMS_PERFORMANCE_READ: "hrms.performance.read",
  HRMS_PERFORMANCE_CREATE: "hrms.performance.create",
  HRMS_PERFORMANCE_UPDATE: "hrms.performance.update",
  HRMS_PERFORMANCE_APPROVE: "hrms.performance.approve",
  HRMS_COMPENSATION_READ: "hrms.compensation.read",
  HRMS_COMPENSATION_CREATE: "hrms.compensation.create",
  HRMS_COMPENSATION_UPDATE: "hrms.compensation.update",
  HRMS_COMPENSATION_APPROVE: "hrms.compensation.approve",
  HRMS_BENEFITS_READ: "hrms.benefits.read",
  HRMS_BENEFITS_CREATE: "hrms.benefits.create",
  HRMS_BENEFITS_UPDATE: "hrms.benefits.update",
  HRMS_BENEFITS_ENROLL: "hrms.benefits.enroll",
  HRMS_COMPLIANCE_READ: "hrms.compliance.read",
  HRMS_COMPLIANCE_CREATE: "hrms.compliance.create",
  HRMS_COMPLIANCE_UPDATE: "hrms.compliance.update",
  HRMS_COMPLIANCE_AUDIT: "hrms.compliance.audit",
  HRMS_ANALYTICS_READ: "hrms.analytics.read",
  HRMS_ANALYTICS_EXPORT: "hrms.analytics.export",
  HRMS_HELPDESK_READ: "hrms.helpdesk.read",
  HRMS_HELPDESK_CREATE: "hrms.helpdesk.create",
  HRMS_HELPDESK_UPDATE: "hrms.helpdesk.update",
  HRMS_HELPDESK_RESOLVE: "hrms.helpdesk.resolve",

  // Hotlist Module (Priority Talent Market)
  HOTLIST_DASHBOARD_VIEW: "hotlist.dashboard.view",
  HOTLIST_CANDIDATES_READ: "hotlist.candidates.read",
  HOTLIST_CANDIDATES_WRITE: "hotlist.candidates.write",
  HOTLIST_CANDIDATES_PACKAGE: "hotlist.candidates.package",
  HOTLIST_CANDIDATES_EXPORT: "hotlist.candidates.export",
  HOTLIST_REQUIREMENTS_READ: "hotlist.requirements.read",
  HOTLIST_REQUIREMENTS_WRITE: "hotlist.requirements.write",
  HOTLIST_REQUIREMENTS_URGENT: "hotlist.requirements.urgent",
  HOTLIST_MATCHES_READ: "hotlist.matches.read",
  HOTLIST_MATCHES_RUN: "hotlist.matches.run",
  HOTLIST_CAMPAIGNS_READ: "hotlist.campaigns.read",
  HOTLIST_CAMPAIGNS_CREATE: "hotlist.campaigns.create",
  HOTLIST_CAMPAIGNS_SEND: "hotlist.campaigns.send",
  HOTLIST_CAMPAIGNS_APPROVE: "hotlist.campaigns.approve",
  HOTLIST_AUTOMATION_READ: "hotlist.automation.read",
  HOTLIST_AUTOMATION_MANAGE: "hotlist.automation.manage",
  HOTLIST_ANALYTICS_VIEW: "hotlist.analytics.view",
  HOTLIST_DLP_OVERRIDE: "hotlist.dlp_override",
  HOTLIST_CONSENT_MANAGE: "hotlist.consent.manage",
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export const ROLES = {
  MASTER_ADMIN: "master_admin",
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  MANAGER: "manager",
  RECRUITER: "recruiter",
  FINANCE: "finance",
  VIEWER: "viewer",
} as const

export type Role = (typeof ROLES)[keyof typeof ROLES]

// Permission groups for easier management
export const PERMISSION_GROUPS = {
  admin: Object.values(PERMISSIONS).filter((p) => p.startsWith("admin.")),
  tenant: Object.values(PERMISSIONS).filter((p) => p.startsWith("tenant.")),
  crm: Object.values(PERMISSIONS).filter((p) => p.startsWith("crm.")),
  talent: Object.values(PERMISSIONS).filter((p) => p.startsWith("talent.")),
  bench: Object.values(PERMISSIONS).filter((p) => p.startsWith("bench.")),
  vms: Object.values(PERMISSIONS).filter((p) => p.startsWith("vms.")),
  finance: Object.values(PERMISSIONS).filter((p) => p.startsWith("finance.")),
  projects: Object.values(PERMISSIONS).filter((p) => p.startsWith("projects.")),
  reports: Object.values(PERMISSIONS).filter((p) => p.startsWith("reports.")),
  settings: Object.values(PERMISSIONS).filter((p) => p.startsWith("settings.")),
  hrms: Object.values(PERMISSIONS).filter((p) => p.startsWith("hrms.")),
  hotlist: Object.values(PERMISSIONS).filter((p) => p.startsWith("hotlist.")),
}
