version: 2

sources:
  - name: raw
    description: "Raw CDC change streams from Supabase Postgres"
    database: nino360
    schema: raw
    tables:
      # Finance
      - name: finance_invoices_changes
        description: "Invoice change events"
        freshness:
          warn_after: {count: 30, period: minute}
          error_after: {count: 60, period: minute}
      - name: finance_payments_changes
      - name: finance_expenses_changes
      - name: finance_timesheets_changes
      
      # ATS
      - name: ats_applications_changes
      - name: ats_candidates_changes
      - name: ats_jobs_changes
      - name: ats_interviews_changes
      
      # Bench
      - name: bench_consultants_changes
      - name: bench_submissions_changes
      - name: bench_placements_changes
      
      # VMS
      - name: vms_vendors_changes
      - name: vms_contracts_changes
      - name: vms_invoices_changes
      
      # HRMS
      - name: hr_employees_changes
      - name: hr_assignments_changes
      - name: hr_attendance_changes
      
      # Projects
      - name: proj_projects_changes
      - name: proj_tasks_changes
      - name: proj_time_entries_changes
      
      # CRM
      - name: crm_accounts_changes
      - name: crm_opportunities_changes
      - name: crm_contacts_changes
      
      # Hotlist
      - name: hot_candidates_changes
      - name: hot_requirements_changes
      - name: hot_matches_changes
      
      # LMS
      - name: lms_enrollments_changes
      - name: lms_progress_changes
      - name: lms_certificates_changes
